server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  # Proxy para o backend (se quiser servir pelo mesmo domínio)
  location /api/ {
    proxy_pass http://backend:8080;
  }
}
